In [3]:
import numpy as np

a = np.array(0)
print("0D --> ", a)

0D -->  0


In [4]:
import numpy as np
b = np.array([1,2,3])
print("1D --> ", b)

1D -->  [1 2 3]


In [14]:
import numpy as np
c = np.array([[1,2,3], [4,5,6],[7,8,9]])
print("2D --> printed below\n", c)

2D --> printed below
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D --> printed below\n", d)

3D --> printed below
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
